apiVersion: v1
kind: Service
metadata:
  name: llm-model-service
spec:
  selector:
    app: model-service-api
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 30081
  type: NodePort