apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-backend-service
  labels:
    app: backend-service-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-service-api
  template:
    metadata:
      labels:
        app: backend-service-api
    spec:
      containers:
        - name: backend-api
          image: backend-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
